[package]
name = "hello"
version = "0.1.0"
authors = ["Kyle Burton <kyle.burton@gmail.com>"]

[dependencies]

[lib]
name = "hellolib"
path = "src/hellolib.rs"

[[bin]]
name = "hellobin"
path = "src/main.rs"
