book(enders_game, orson_scott_card).
book(speaker_for_the_dead, orson_scott_card).
book(the_three_body_prlblem, liu_cixin).
book(the_dark_forest, liu_cixin).
book(the_hitchhikers_guide_to_the_universe, douglas_adams).
book(the_restaurant_at_the_end_of_the_universe, douglas_adams).
book(life_the_universe_and_everything, douglas_adams).
book(so_long_and_thanks_for_all_the_fish, douglas_adams).
book(mostly_harmless, douglas_adams).
book(dirk_gentlys_holistic_detective_agency, douglas_adams).
book(the_long_dark_teatime_of_the_soul, douglas_adams).
book(the_omnivores_dilemma, michael_pollan).
book(freakonomics, dubner_and_levit).
book(how_to_play_with_your_food, penn_and_teller).
book(paip, peter_norvig).
book(the_22_immutable_laws_of_marketing, al_ries).
book(the_pragmatic_programmer, hunt_and_thomas).
book(surely_youre_joking_mr_feynman, richard_p_feynman).
book(neverwhere, neil_gaiman).
book(american_gods, neil_gaiman).
book(the_ocean_at_the_end_of_the_lane, neil_gaiman).
book(stardust, neil_gaiman).
book(anansi_boys, neil_gaiman).
book(the_graveyard_book, neil_gaiman).
