#!/usr/bin/env bash
DBFILE="flaskr/db/flaskr.db"

bake_task run
function run () {
  cd flaskr
  python flaskr.py
}

bake_task dbshell
function dbshell () {
  sqlite3 $DBFILE
}

bake_task shell
function shell () {
  cd flaskr
  python
}

bake_task run_tests
function run_tests () {
  cd flaskr
  python flaskr_tests.py
}
