#!/usr/bin/env python3
"""
Parses a Linux `input-event-codes.h` header and emits a constants.h/constants.c
pair containing name lookup tables for the `type`, `code` and `value` fields
of `struct input_event`.

Usage: gen_input_constants.py <input-event-codes.h> <constants.h> <constants.c>
"""
import re
import sys
from datetime import datetime, timezone

DEFINE_RE = re.compile(r'^#define\s+([A-Za-z_][A-Za-z0-9_]*)\s+(0[xX][0-9a-fA-F]+|[0-9]+)\b')

# Each group: prefix to match against a #define name, the C array/ident base
# name, the CNT macro used to size the array, and the EV_* type that dispatches
# to this table (None for the EV_* table itself, which backs the type lookup).
GROUPS = [
    {"prefix": "EV_",  "ident": "ev_type", "cnt": "EV_CNT",  "ev_type": None},
    {"prefix": "SYN_", "ident": "syn",     "cnt": "SYN_CNT", "ev_type": "EV_SYN"},
    {"prefix": "KEY_", "ident": "key",     "cnt": "KEY_CNT", "ev_type": "EV_KEY"},
    {"prefix": "BTN_", "ident": "key",     "cnt": "KEY_CNT", "ev_type": "EV_KEY"},
    {"prefix": "REL_", "ident": "rel",     "cnt": "REL_CNT", "ev_type": "EV_REL"},
    {"prefix": "ABS_", "ident": "abs",     "cnt": "ABS_CNT", "ev_type": "EV_ABS"},
    {"prefix": "SW_",  "ident": "sw",      "cnt": "SW_CNT",  "ev_type": "EV_SW"},
    {"prefix": "MSC_", "ident": "msc",     "cnt": "MSC_CNT", "ev_type": "EV_MSC"},
    {"prefix": "LED_", "ident": "led",     "cnt": "LED_CNT", "ev_type": "EV_LED"},
    {"prefix": "SND_", "ident": "snd",     "cnt": "SND_CNT", "ev_type": "EV_SND"},
    {"prefix": "REP_", "ident": "rep",     "cnt": "REP_CNT", "ev_type": "EV_REP"},
]


def group_for(name):
    # longest-prefix match first so e.g. a future FOO_BAR_ prefix can't
    # shadow FOO_
    for group in sorted(GROUPS, key=lambda g: -len(g["prefix"])):
        if name.startswith(group["prefix"]):
            bound_name = group["prefix"] + "MAX"
            if name == bound_name:
                return None  # the *_MAX bound marker itself, not a real code
            return group
    return None


def parse_defines(header_path):
    entries = {}  # ident -> list of (name, group)
    seen_values = {}  # ident -> set of numeric values already emitted
    with open(header_path) as f:
        for line in f:
            m = DEFINE_RE.match(line)
            if not m:
                continue
            name = m.group(1)
            group = group_for(name)
            if group is None:
                continue
            ident = group["ident"]
            value = int(m.group(2), 0)
            # several names alias the same numeric code (e.g. BTN_MISC ==
            # BTN_0); keep only the first name seen for a given value so the
            # designated initializers below don't collide.
            values = seen_values.setdefault(ident, set())
            if value in values:
                continue
            values.add(value)
            entries.setdefault(ident, []).append((name, group))
    return entries


def render_header(out_path):
    with open(out_path, "w") as f:
        f.write(
            "/* AUTO-GENERATED by scripts/gen_input_constants.py -- DO NOT EDIT BY HAND */\n"
            "#ifndef CONSTANTS_H\n"
            "#define CONSTANTS_H\n\n"
            "const char* input_event_type_name(unsigned int type);\n"
            "const char* input_event_code_name(unsigned int type, unsigned int code);\n"
            "const char* input_event_value_name(unsigned int type, int value);\n\n"
            "#endif\n"
        )


def render_source(out_path, header_path, entries):
    ident_groups = {}
    for ident, items in entries.items():
        for name, group in items:
            ident_groups[ident] = group

    lines = []
    lines.append("/* AUTO-GENERATED by scripts/gen_input_constants.py -- DO NOT EDIT BY HAND */")
    lines.append(f"/* Source header: {header_path} */")
    lines.append(f"/* Generated: {datetime.now(timezone.utc).strftime('%FT%TZ')} */")
    lines.append("")
    lines.append('#include "constants.h"')
    lines.append("#include <linux/input-event-codes.h>")
    lines.append("#include <stddef.h>")
    lines.append("")

    # emit one static name table per group ident, e.g. "key" -> key_names[KEY_CNT]
    for ident in sorted(entries):
        group = ident_groups[ident]
        lines.append(f"static const char *{ident}_names[{group['cnt']}] = {{")
        for name, _ in entries[ident]:
            lines.append(f'  [{name}] = "{name}",')
        lines.append("};")
        lines.append("")

    # type_name() looks up the ev_type table directly
    lines.append("const char* input_event_type_name(unsigned int type) {")
    lines.append("  if (type < EV_CNT && ev_type_names[type] != NULL) {")
    lines.append("    return ev_type_names[type];")
    lines.append("  }")
    lines.append('  return "UNKNOWN";')
    lines.append("}")
    lines.append("")

    # code_name() dispatches on type to the matching table
    lines.append("const char* input_event_code_name(unsigned int type, unsigned int code) {")
    lines.append("  switch (type) {")
    seen_idents = set()
    for group in GROUPS:
        if group["ev_type"] is None:
            continue
        ident = group["ident"]
        if ident not in entries or ident in seen_idents:
            continue
        seen_idents.add(ident)
        lines.append(f"    case {group['ev_type']}:")
        lines.append(f"      if (code < {group['cnt']} && {ident}_names[code] != NULL) {{")
        lines.append(f"        return {ident}_names[code];")
        lines.append("      }")
        lines.append("      break;")
    lines.append("    default:")
    lines.append("      break;")
    lines.append("  }")
    lines.append('  return "UNKNOWN";')
    lines.append("}")
    lines.append("")

    # value_name() is hand-modeled: only EV_KEY values are a small enumerable
    # set (the header does not name these), everything else is analog/raw.
    lines.append("const char* input_event_value_name(unsigned int type, int value) {")
    lines.append("  if (type == EV_KEY) {")
    lines.append("    switch (value) {")
    lines.append('      case 0: return "RELEASED";')
    lines.append('      case 1: return "PRESSED";')
    lines.append('      case 2: return "REPEATED";')
    lines.append("      default: break;")
    lines.append("    }")
    lines.append("  }")
    lines.append("  return NULL;")
    lines.append("}")
    lines.append("")

    with open(out_path, "w") as f:
        f.write("\n".join(lines))


def main():
    if len(sys.argv) != 4:
        print(f"usage: {sys.argv[0]} <input-event-codes.h> <constants.h> <constants.c>",
              file=sys.stderr)
        return 1

    header_path, out_h, out_c = sys.argv[1:4]
    entries = parse_defines(header_path)
    render_header(out_h)
    render_source(out_c, header_path, entries)
    return 0


if __name__ == "__main__":
    sys.exit(main())
