#!/usr/bin/env bash

bake_require github.com/kyleburton/bake-recipes/emacs/cider.sh

bake_task run_emacs
function run_emacs () {
  emacs -nw -q -l "$HOME/.bake/packages/github.com/kyleburton/bake-recipies/files/emacs/.emacs" "$@"
}

bake_task open_file
function open_file () {
  local fname="$1"
  if which gnome-open; then
    gnome-open "$fname"
    return
  fi

  open "$fname"
}

bake_task render_graph
function render_graph () {
  local dotfile pngfile
  dotfile="${1:-$(ls -t -1 *.dot | head -n 1)}"
  pngfile="$(basename "$dotfile" .dot).png"
  dot "$dotfile" -Tpng > "$pngfile" && open_file "$pngfile"
}


bake_task nrepl
function nrepl () {
  clojure -Sdeps '{:deps {nrepl/nrepl {:mvn/version "0.6.0"} cider/cider-nrepl {:mvn/version "0.25.5"}}}' -m nrepl.cmdline --middleware '["cider.nrepl/cider-middleware"]'
}
