#!/usr/bin/env bash

set -eEuo pipefail

[[ -n "${DEBUG:-}" ]] && set -x

bake_task new "New Cargo Project"
function new () {
    local name
    name="$1"

    if [[ -z "$name" ]]; then
        >&2 echo "Error: missing project 'name'"
        return 1
    fi

    cargo new "$name"
    cat <<EOF  > "$name"/.gitignore
target/
EOF
    cat <<EOF  > "$name"/Bakefile
#!/usr/bin/env bash
set -eEuo pipefail
bake_task run "build and run the project"
function run () {
    clear
    cargo b && "./target/debug/$name"
}

bake_default_task run
EOF
    touch "$name"/Cargo.lock
    (
        cd "$name"
        cargo b && "./target/debug/$name"
        git add .
#         cat <<EOF > .tmp.bashrc
# source ~/.bashrc
# PS1="inference: \$PS1 "
# EOF
#         echo "don't forget to exit the subshell"
#         bash --rcfile .tmp.bashrc
    )
    echo "cd \"$name\""
}
