[package]
name = "connect"
version = "0.1.0"
authors = ["Kyle Burton <kyle.burton@gmail.com>"]

[dependencies]
r2d2 = "0.7.0"
r2d2_postgres = "0.10.1"
rustc-serialize = "0.3"
postgres = {version = "0.11.8", features = [ "openssl" ] }
openssl = "0.7.13"

