#!/usr/bin/env bash

DOCKER_IMAGE_TAG="mysql:latest"
DOCKER_IMAGE_NAME="simplemigrate-mysql"

#bake_require $HOME/personal/projects/bake-recipes/docker/docker.sh
source $HOME/personal/projects/bake-recipes/docker/docker.sh

bake_require ./migrations.sh
DEBUG="${DEBUG:-}"

if [ -n "$DEBUG" ]; then
  set -x
fi

