#!/usr/bin/env bash

bake_require src/sh/dev

bake_task lmacs "Run the local emacs configuration"
function lmacs () {
  emacs -nw "$@" --no-init-file --load .emacs
}

bake_task install
function install () {
  test -d software || mkdir software
  install_cider
  install_ac_cider
  install_lein
  install_lein_kinematic_app_template
  install_go
}

bake_task gen-web-service 
function gen-web-service () {
    lein new kinematic-app web-service
}
