#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook "packages", 
         :git  => "https://github.com/kyleburton/chef-cookbooks.git",
         :path => "packages"
cookbook "openresty-nginx", 
         :git  => "https://github.com/kyleburton/chef-cookbooks.git",
         :path => "openresty-nginx"
cookbook "bash_profile", 
         :git  => "https://github.com/kyleburton/chef-cookbooks.git",
         :path => "bash_profile"

# cookbook 'chef-client'

# cookbook 'apache2', '>= 1.0.0'

# cookbook 'rvm',
#   :git => 'https://github.com/fnichol/chef-rvm'

# cookbook 'postgresql',
#   :git => 'https://github.com/findsyou/cookbooks',
#   :ref => 'postgresql-improvements'
