#!/usr/bin/env bash

bake_task init "Init / Bootstrap the project"
function init () {
  test -f package.json || npm --init 

  if ! npm ls webpack; then
    npm i webpack -S
  fi

  if ! npm ls babel-loader; then
    npm i babel-loader babel-preset-es2015 babel-preset-react -S
  fi

  if [ ! -e webpack.config.js ]; then
    cat <<END > webpack.config.js
var webpack = require('webpack');
var path = require('path');

var BUILD_DIR = path.resolve(__dirname, 'src/client/public');
var APP_DIR = path.resolve(__dirname, 'src/client/app');

var config = {
  entry: APP_DIR + '/index.jsx',
  output: {
    path: BUILD_DIR,
    filename: 'bundle.js'
  }
};

module.exports = config;
END
  fi

  if [ ! -e src/client/index.html ]; then
    cat <<END > src/client/index.html
<html>
  <head>
    <meta charset="utf-8">
    <title>React.js using NPM, Babel6 and Webpack</title>
  </head>
  <body>
    <div id="app" />
    <script src="public/bundle.js" type="text/javascript"></script>
  </body>
</html>
END
  fi
}

bake_task dev-build ""
function dev-build () {
  ./node_modules/.bin/webpack -d
}
