#!/usr/bin/env bash
bake_task run
function run () {
  clang++ \
    -std=c++14 \
    -stdlib=libc++ \
    -Weverything \
    -Wno-c++98-c++11-compat-pedantic \
    -Wno-c++98-compat \
    -o main \
    main.cpp
  ./main
}

