CONFIG = {
  :pacakge_url => ""
}

unless File.exist? "nginx"
  FileUtils.mkdir "nginx"
end

namespace :nginx do
  desc "Downlaod the server"
  task :download do
    raise "download: implement this"
  end

  desc "Install the server"
  task :install => [:download] do
    raise "install: implement this"
  end

  desc "Run the server"
  task :server => [:install] do
    raise "server: implement this"
  end
end
