#!/usr/bin/env bash
INSTAL_PATH=/cygdrive/c/Users/kyle/AppData/Roaming/.minecraft

MINECRAFT_SERVER_JAR_URL="https://s3.amazonaws.com/Minecraft.Download/versions/1.8.3/minecraft_server.1.8.3.jar"

BAKCUP_DIR="$HOME/local/minecraft"

function isodate () {
  date -u +"%Y-%m-%dT%H:%M:%SZ"
}

bake_task sync
function sync () {
  test -d data || mkdir data
  cd data
  rsync -avz $INSTAL_PATH/saves ./
}

bake_task backup
function backup () {
  set -exu
  bake_echo_red "Make sure the server is stopped first..."
  echo -n "Press Enter: "
  read FOO
  test -d "$BAKCUP_DIR" || mkdir $BAKCUP_DIR
  cd "$BAKCUP_DIR"
  rsync -avz "$(bake_bakefile_dir)" ./
  local bname="${1:-backup}"
  local logmsg="$(isodate): $bname"
  # sync
  test -d .git || git init
  git add .
  git commit -m "$logmsg"
}

bake_task restore 
function restore () {
  cd data
  rsync -avz ./saves $INSTAL_PATH/
}

bake_task install
function install () {
  local jfile="$(basename $MINECRAFT_SERVER_JAR_URL)"
  test -f  $jfile || wget $MINECRAFT_SERVER_JAR_URL
}


bake_task install_sun_jdk
function install_sun_jdk () {
  sudo apt-add-repository ppa:webupd8team/java
  sudo apt-get update
  sudo apt-get install oracle-java7-installer
}

bake_task run_server
function run_server () {
  #jvm_args="-Xmx3G -Xms3G -Xmn768m -XX:+DisableExplicitGC -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+UseNUMA -XX:+CMSParallelRemarkEnabled -XX:MaxTenuringThreshold=15 -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+UseAdaptiveGCBoundary -XX:-UseGCOverheadLimit -XX:+UseBiasedLocking -XX:SurvivorRatio=8 -XX:TargetSurvivorRatio=90 -XX:MaxTenuringThreshold=15 -Dfml.ignorePatchDiscrepancies=true -Dfml.ignoreInvalidMinecraftCertificates=true -XX:+UseFastAccessorMethods -XX:+UseCompressedOops -XX:+OptimizeStringConcat -XX:+AggressiveOpts -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:SoftRefLRUPolicyMSPerMB=10000 -XX:parallelGCThreads=10"
  jvm_args="-Xmx3G -Xms3G -Xmn768m -XX:MaxGCPauseMillis=30 -XX:GCPauseIntervalMillis=150 -XX:+OptimizeStringConcat"
  jfile="$(basename $MINECRAFT_SERVER_JAR_URL)"
  # java -Xms512M -Xmx1024M -jar $jfile nogui
  set -x
  java $jvm_args -jar $jfile nogui
}

