#!/usr/bin/env bash

bake_require github.com/kyleburton/bake-recipies/emacs/cider.sh

INSTAL_PATH=/cygdrive/c/Users/kyle/AppData/Roaming/.minecraft
MINECRAFT_SERVER_JAR_URL="https://s3.amazonaws.com/Minecraft.Download/versions/1.8.3/minecraft_server.1.8.3.jar"
BAKCUP_DIR="$HOME/local/minecraft"
LTPWMP_CODE="http://media.pragprog.com/titles/ahmine2/code/ahmine2-code.zip"
CANARYMOD_VERSION="1.2.0"
CANARYMOD_JAR="CanaryMod-$CANARYMOD_VERSION.jar"

bake_task download_ltpwmp
function download_ltpwmp () {
  local fname="$(basename $LTPWMP_CODE)"
  wget --continue $LTPWMP_CODE
  test -d ahmine2-code || mkdir ahmine2-code
  cd ahmine2-code
  test -d code || unzip ../$fname
}

bake_task download_canarymod_jar
function download_canarymod_jar () {
  set -x
  if [ ! -f "$CANARYMOD_JAR" ]; then

    local furl=$(curl "http://canarymod.net/releases" | perl -ne 'print "$1\n" if m|<a href="([^"]+)">CanaryMod-1.2.0.jar</a>|ms')
    curl "http://canarymod.net$furl" > CanaryMod-$CANARYMOD_VERSION.jar
  fi
}

function isodate () {
  date -u +"%Y-%m-%dT%H:%M:%SZ"
}

bake_task sync
function sync () {
  test -d data || mkdir data
  cd data
  rsync -avz $INSTAL_PATH/saves ./
}

bake_task backup
function backup () {
  bake_echo_red "Make sure the server is stopped first..."
  echo -n "Press Enter: "
  read FOO
  test -d "$BAKCUP_DIR" || mkdir $BAKCUP_DIR
  cd "$BAKCUP_DIR"
  rsync "$(bake_bakefile_dir)" ./
  bash
  local bname="${1:-backup}"
  local logmsg="$(isodate): $bname"
  sync
  test -d .git || git init
  git add .
  git commit -m "$logmsg"
}

bake_task restore 
function restore () {
  cd data
  rsync -avz ./saves $INSTAL_PATH/
}

bake_task install
function install () {
  local jfile="$(basename $MINECRAFT_SERVER_JAR_URL)"
  test -f  $jfile || wget $MINECRAFT_SERVER_JAR_URL
}


bake_task install_sun_jdk
function install_sun_jdk () {
  sudo apt-add-repository ppa:webupd8team/java
  sudo apt-get update
  sudo apt-get install oracle-java7-installer
}

bake_task run_standard_server
function run_standard_server () {
  jfile="$(basename $MINECRAFT_SERVER_JAR_URL)"
  java -Xms512M -Xmx1024M -jar $jfile nogui
}


bake_task run_canarymod_server
function run_canarymod_server () {
  set -x
  if grep -q "eula=false" eula.txt; then
    echo "Error: you have to accept the EULA, see the file eula.txt"
    return 1
  fi
  java -cp "$(lein classpath)" -Xms1024M -Xmx1024M net.canarymod.Main
}

bake_task mvn_install_canarymod
function mvn_install_canarymod () {
  mvn install:install-file -Dfile=$CANARYMOD_JAR -DgroupId=canarymod \
    -DartifactId=canarymod -Dversion=$CANARYMOD_VERSION -Dpackaging=jar
}
