#!/usr/bin/env bash
#set -x
bake_push_libdir $(bake_bakefile_dir)/src/sh
bake_require erlang
bake_require_git https://github.com/kyleburton/bake-recipies.git emacs/cider.sh

source src/sh/python.sh
source src/sh/oracle-java.sh
source src/sh/leiningen.sh
source src/sh/os-utils.sh
source src/sh/profile.sh
source src/sh/linuxbrew.sh
source src/sh/rust.sh

bake_task write-env-sh "Create the env.sh file"
function write-env-sh () {
  sort -u .path.dirs > .path.dirs.new
  mv -f .path.dirs.new .path.dirs
  P="$(echo $(sort -u .path.dirs) | tr ' ' :)"
  echo "PATH=$P:\$PATH" > env.sh
}

function add_path () {
  if [ -z "$1" ]; then
    echo "Sorry, you must pass a path to add_path!"   
    exit 1
  fi

  echo "$1" >> .path.dirs
  write-env-sh
}

bake_task install-all "Install all the goodies."
function install-all () {
  erlang-install-all
}
