#!/usr/bin/env bash

set -eEuo pipefail

bake_task init
function init {
  test -d ./software || mkdir ./software
  (
  cd ./software
  if [[ ! -f ./quicklisp.lisp ]]; then
    curl -O https://beta.quicklisp.org/quicklisp.lisp
    sbcl \
      --no-sysinit \
      --no-userinit \
      --load ./quicklisp.lisp \
      --eval '(quicklisp-quickstart:install :path "../.quicklisp")' \
      --eval '(ql:add-to-init-file)' \
      --quit
  fi
)
}
