version: "3.7"

volumes:
  pgdata-volume:
services:
  postgres:
    image: "postgres:11"
    environment:
      - POSTGRE_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=etest
      - PGDAT=/pgdata
    volumes:
      - pgdata-volume:/pgdata
