#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -sname kburton@localhost -setcookie riotgames -pa ~/.riot.d/erlang
%%
%% see: http://stratus3d.com/blog/2016/07/02/escript-essentials/
%% see: https://github.com/jcomellas/getopt
%% see: https://stackoverflow.com/questions/6545416/escript-setting-code-path-relative-to-script-directory
%%      true = code:add_pathz(filename:dirname(escript:script_name())
%%                          ++ "/../dir-of-some-beams"),
%%

%% Eg: ./consult this that other
write_terms(FileName, List) ->
    Format = fun(Term) -> io_lib:format("~tp.~n", [Term]) end,
    Text = lists:map(Format, List),
    file:write_file(FileName, Text).

main(_Args) ->
    FileName = "input.erlang",
    write_terms(FileName,
                [{person, [{name,"Mario"},  {height,"short"}]},
                 {person, [{name,"Peach"},  {height,"average"}]},
                 {person, [{name,"Bowser"}, {height,"huge"}]},
                 {person, [{name,"Luigi"},  {height,"tall"}]}]),
    {ok, Terms} = file:consult(FileName),
    lists:foreach(
      fun(Term) ->
              io:format("Term=~p~n", [Term])
      end,
      Terms
     ),
    halt(0).
