#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -sname kburton@localhost -setcookie riotgames -pa ~/.riot.d/erlang
%%
%% see: http://stratus3d.com/blog/2016/07/02/escript-essentials/
%% see: https://github.com/jcomellas/getopt
%% see: https://stackoverflow.com/questions/6545416/escript-setting-code-path-relative-to-script-directory
%%      true = code:add_pathz(filename:dirname(escript:script_name())
%%                          ++ "/../dir-of-some-beams"),
%%

%% Eg: ./write this that other

main(_Args) ->
    FileName = "output.txt",
    Contents = <<"
This is the sample.
text file
">>,
    ok = file:write_file(FileName, Contents),
    io:format("Have a look at: ~p~n", [FileName]),
    halt(0).
