(ns com.github.kyleburton.sandbox.regex
  (:import (java.util.regex Pattern Matcher))
  (:use [com.github.kyleburton.sandbox.utils :as kutils])
  (:use [clojure.contrib.str-utils :as str]
        [clojure.contrib.fcase :only (case)]))

(def *us-states* 
     {"AL" "ALABAMA"
      "AK" "ALASKA"
      "AS" "AMERICAN SAMOA"
      "AZ" "ARIZONA"
      "AR" "ARKANSAS"
      "CA" "CALIFORNIA"
      "CO" "COLORADO"
      "CT" "CONNECTICUT"
      "DE" "DELAWARE"
      "DC" "DISTRICT OF COLUMBIA"
      "FM" "FEDERATED STATES OF MICRONESIA"
      "FL" "FLORIDA"
      "GA" "GEORGIA"
      "GU" "GUAM"
      "HI" "HAWAII"
      "ID" "IDAHO"
      "IL" "ILLINOIS"
      "IN" "INDIANA"
      "IA" "IOWA"
      "KS" "KANSAS"
      "KY" "KENTUCKY"
      "LA" "LOUISIANA"
      "ME" "MAINE"
      "MH" "MARSHALL ISLANDS"
      "MD" "MARYLAND"
      "MA" "MASSACHUSETTS"
      "MI" "MICHIGAN"
      "MN" "MINNESOTA"
      "MS" "MISSISSIPPI"
      "MO" "MISSOURI"
      "MT" "MONTANA"
      "NE" "NEBRASKA"
      "NV" "NEVADA"
      "NH" "NEW HAMPSHIRE"
      "NJ" "NEW JERSEY"
      "NM" "NEW MEXICO"
      "NY" "NEW YORK"
      "NC" "NORTH CAROLINA"
      "ND" "NORTH DAKOTA"
      "MP" "NORTHERN MARIANA ISLANDS"
      "OH" "OHIO"
      "OK" "OKLAHOMA"
      "OR" "OREGON"
      "PW" "PALAU"
      "PA" "PENNSYLVANIA"
      "PR" "PUERTO RICO"
      "RI" "RHODE ISLAND"
      "SC" "SOUTH CAROLINA"
      "SD" "SOUTH DAKOTA"
      "TN" "TENNESSEE"
      "TX" "TEXAS"
      "UT" "UTAH"
      "VT" "VERMONT"
      "VI" "VIRGIN ISLANDS"
      "VA" "VIRGINIA"
      "WA" "WASHINGTON"
      "WV" "WEST VIRGINIA"
      "WI" "WISCONSIN"
      "WY" "WYOMING"
      "AE" "Armed Forces Africa"
      "AA" "Armed Forces Americas"
      "AE" "Armed Forces Europe"
      "AE" "Armed Forces Middle East"
      "AP" "Armed Forces Pacific"
      })

(def *us-airport-codes*
     (partition 
      3 
      ["SD" "Aberdeen" "ABR"
       "TX" "Abilene" "ABI"
       "AK" "Adak Island" "ADK"
       "AK" "Akiachak" "KKI"
       "AK" "Akiak" "AKI"
       "OH" "Akron/Canton" "CAK"
       "AK" "Akuton" "KQA"
       "AK" "Alakanuk" "AUK"
       "NM" "Alamogordo" "ALM"
       "CO" "Alamosa" "ALS"
       "NY" "Albany" "ALB"
       "OR - Bus service" "Albany" "CVO"
       "OR - Bus service" "Albany" "QWY"
       "NM" "Albuquerque" "ABQ"
       "AK" "Aleknagik" "WKK"
       "LA" "Alexandria" "AEX"
       "AK" "Allakaket" "AET"
       "PA" "Allentown" "ABE"
       "NE" "Alliance" "AIA"
       "MI" "Alpena" "APN"
       "PA" "Altoona" "AOO"
       "TX" "Amarillo" "AMA"
       "AK" "Ambler" "ABL"
       "AK" "Anaktueuk" "AKP"
       "AK" "Anchorage" "ANC"
       "AK" "Angoon" "AGN"
       "AK" "Aniak" "ANI"
       "AK" "Anvik" "ANV"
       "WI" "Appleton" "ATW"
       "CA" "Arcata" "ACV"
       "AK" "Arctic Village" "ARC"
       "NC" "Asheville" "AVL"
       "KY/Huntington, WV" "Ashland" "HTS"
       "CO" "Aspen" "ASE"
       "GA" "Athens" "AHN"
       "AK" "Atka" "AKB"
       "GA" "Atlanta" "ATL"
       "NJ" "Atlantic City" "AIY"
       "AK" "Atqasuk" "ATK"
       "GA" "Augusta" "AGS"
       "ME" "Augusta" "AUG"
       "TX" "Austin" "AUS"
       "CA" "Bakersfield" "BFL"
       "MD" "Baltimore" "BWI"
       "ME" "Bangor" "BGR"
       "ME" "Bar Harbour" "BHB"
       "AK" "Barrow" "BRW"
       "AK" "Barter Island" "BTI"
       "LA" "Baton Rouge" "BTR"
       "MI" "Bay City" "MBS"
       "TX" "Beaumont/Port Arthur" "BPT"
       "CO - Van service" "Beaver Creek" "ZBV"
       "AK" "Beaver" "WBQ"
       "WV" "Beckley" "BKW"
       "MA" "Bedford" "BED"
       "IL" "Belleville" "BLV"
       "WA" "Bellingham" "BLI"
       "MN" "Bemidji" "BJI"
       "MI" "Benton Harbor" "BEH"
       "AK" "Bethel" "BET"
       "PA" "Bethlehem" "ABE"
       "AK" "Bettles" "BTT"
       "MT" "Billings" "BIL"
       "MS" "Biloxi/Gulfport" "GPT"
       "NY" "Binghamton" "BGM"
       "AK" "Birch Creek" "KBC"
       "AL" "Birmingham" "BHM"
       "ND" "Bismarck" "BIS"
       "RI" "Block Island" "BID"
       "IL" "Bloomington" "BMI"
       "WV" "Bluefield" "BLF"
       "ID" "Boise" "BOI"
       "MA" "Boston" "BOS"
       "CO - Bus service" "Boulder" "XHH"
       "CO - Hiltons Har H" "Boulder" "WHH"
       "CO - Municipal Airport" "Boulder" "WBU"
       "AK" "Boundary" "BYA"
       "KY" "Bowling Green" "BWG"
       "MT" "Bozeman" "BZN"
       "PA" "Bradford" "BFD"
       "MN" "Brainerd" "BRD"
       "TX" "Brawnwood" "BWD"
       "CO - Van service" "Breckonridge" "QKB"
       "VA" "Bristol" "TRI"
       "SD" "Brookings" "BKX"
       "AK" "Brooks Lodge" "RBH"
       "TX" "Brownsville" "BRO"
       "GA" "Brunswick" "BQK"
       "AK" "Buckland" "BKC"
       "NY" "Buffalo" "BUF"
       "AZ" "Bullhead City/Laughlin" "IFP"
       "CA" "Burbank" "BUR"
       "IA" "Burlington" "BRL"
       "VT" "Burlington" "BTV"
       "MT" "Butte" "BTM"
       "OH" "Canton/Akron" "CAK"
       "MO" "Cape Girardeau" "CGI"
       "AK" "Cape Lisburne" "LUR"
       "AK" "Cape Newenham" "EHM"
       "IL" "Carbondale" "MDH"
       "CA" "Carlsbad" "CLD"
       "NM" "Carlsbad" "CNM"
       "CA" "Carmel" "MRY"
       "WY" "Casper" "CPR"
       "UT" "Cedar City" "CDC"
       "IA" "Cedar Rapids" "CID"
       "AK" "Central" "CEM"
       "NE" "Chadron" "CDR"
       "AK" "Chalkyitsik" "CIK"
       "IL" "Champaign/Urbana" "CMI"
       "SC" "Charleston" "CHS"
       "WV" "Charleston" "CRW"
       "NC" "Charlotte" "CLT"
       "VA" "Charlottesville" "CHO"
       "TN" "Chattanooga" "CHA"
       "AK" "Chefornak" "CYF"
       "AK" "Chevak" "VAK"
       "WY" "Cheyenne" "CYS"
       "IL - Meigs" "Chicago" "CGX"
       "IL - All airports" "Chicago" "CHI"
       "IL - Midway" "Chicago" "MDW"
       "IL - O'Hare" "Chicago" "ORD"
       "AK" "Chicken" "CKX"
       "CA" "Chico" "CIC"
       "AK - Fisheries" "Chignik" "KCG"
       "AK -" "Chignik" "KCQ"
       "AK - Lagoon" "Chignik" "KCL"
       "AK" "Chisana" "CZN"
       "MN" "Chisholm/Hibbing" "HIB"
       "AK" "Chuathbaluk" "CHU"
       "OH" "Cincinnati" "CVG"
       "AK" "Circle Hot Springs" "CHP"
       "AK" "Circle" "IRC"
       "AK" "Clarks Point" "CLP"
       "WV" "Clarksburg" "CKB"
       "FL" "Clearwater/St Petersburg" "PIE"
       "OH" "Cleveland" "CLE"
       "NM" "Clovis" "CVN"
       "WY" "Cody/Yellowstone" "COD"
       "AK" "Coffee Point" "CFA"
       "AK" "Coffman Cove" "KCC"
       "AK" "Cold Bay" "CDB"
       "TX" "College Station" "CLL"
       "CO" "Colorado Springs" "COS"
       "MO" "Columbia" "COU"
       "SC" "Columbia" "CAE"
       "GA" "Columbus" "CSG"
       "MS" "Columbus" "GTR"
       "OH" "Columbus" "CMH"
       "CA" "Concord" "CCR"
       "KS" "Concordia" "CNK"
       "CO - Van service" "Copper Mountain" "QCE"
       "AK" "Cordova" "CDV"
       "TX" "Corpus Christi" "CRP"
       "CO" "Cortez" "CEZ"
       "AK" "Craig" "CGA"
       "CA" "Crescent City" "CEC"
       "AK" "Crooked Creek" "CKO"
       "AK" "Cube Cove" "CUW"
       "MD" "Cumberland" "CBE"
       "TX" "Dallas/Fort Worth" "DFW"
       "OH" "Dayton" "DAY"
       "FL" "Daytona Beach" "DAB"
       "IL" "Decatur" "DEC"
       "AK" "Deering" "DRG"
       "AK" "Delta Junction" "DJN"
       "CO - International" "Denver" "DEN"
       "CO - Longmont Bus service" "Denver" "QWM"
       "IA" "Des Moines" "DSM"
       "MI - All airports" "Detroit" "DTT"
       "MI - Metro/Wayne County" "Detroit" "DTW"
       "ND" "Devil's Lake" "DVL"
       "ND" "Dickinson" "DIK"
       "AK" "Dillingham" "DLG"
       "KS" "Dodge City" "DDC"
       "AL" "Dothan" "DHN"
       "PA" "Dubois" "DUJ"
       "IA" "Dubuque" "DBQ"
       "MN" "Duluth" "DLH"
       "CO" "Durango" "DRO"
       "NC" "Durham" "RDU"
       "NC" "Durham/Raleigh" "RDU"
       "AK" "Dutch Harbor" "DUT"
       "PA" "Easton" "ABE"
       "WI" "Eau Claire" "EAU"
       "AK" "Edna Bay" "EDA"
       "AK" "Eek" "EEK"
       "AK" "Ekuk" "KKU"
       "AK" "Ekwok" "KEK"
       "CA" "El Centro" "IPL"
       "AR" "El Dorado" "ELD"
       "TX" "El Paso" "ELP"
       "AK" "Elfin Cove" "ELV"
       "AK" "Elim" "ELI"
       "NV" "Elko" "EKO"
       "NY" "Elmira" "ELM"
       "MN" "Ely" "LYU"
       "AK" "Emmonak" "EMK"
       "NY" "Endicott" "BGM"
       "OK" "Enid" "WDG"
       "PA" "Erie" "ERI"
       "MI" "Escanaba" "ESC"
       "OR" "Eugene" "EUG"
       "CA" "Eureka/Arcata" "ACV"
       "NV" "Eureka" "EUE"
       "IN" "Evansville" "EVV"
       "AK" "Fairbanks" "FAI"
       "ND" "Fargo" "FAR"
       "AR - Municipal/Drake" "Fayetteville" "FYV"
       "AR - Northwest Arkansas Regional" "Fayetteville" "XNA"
       "NC" "Fayetteville" "FAY"
       "AZ" "Flagstaff" "FLG"
       "MI" "Flint" "FNT"
       "SC" "Florence" "FLO"
       "AL" "Florence/Muscle Shoals/Sheffield" "MSL"
       "CO - Municipal Airport" "Fort Collins/Loveland" "FNL"
       "CO - Bus service" "Fort Collins/Loveland" "QWF"
       "IA" "Fort Dodge" "FOD"
       "FL" "Fort Lauderdale" "FLL"
       "MO" "Fort Leonard Wood" "TBN"
       "FL" "Fort Myers" "RSW"
       "AR" "Fort Smith" "FSM"
       "FL" "Fort Walton Beach" "VPS"
       "IN" "Fort Wayne" "FWA"
       "TX" "Fort Worth/Dallas" "DFW"
       "PA" "Franklin" "FKL"
       "CA" "Fresno" "FAT"
       "FL" "Gainesville" "GNV"
       "NM" "Gallup" "GUP"
       "KS" "Garden City" "GCK"
       "IN" "Gary" "GYY"
       "WY" "Gillette" "GCC"
       "TX" "Gladewater/Kilgore" "GGG"
       "MT" "Glasgow" "GGW"
       "MT" "Glendive" "GDV"
       "AK" "Golovin" "GLV"
       "AK" "Goodnews Bay" "GNU"
       "AZ - Heliport" "Grand Canyon" "JGC"
       "AZ - National Park" "Grand Canyon" "GCN"
       "ND" "Grand Forks" "GFK"
       "NE" "Grand Island" "GRI"
       "CO" "Grand Junction" "GJT"
       "MI" "Grand Rapids" "GRR"
       "MN" "Grand Rapids" "GPZ"
       "AK" "Grayling" "KGX"
       "MT" "Great Falls" "GTF"
       "WI" "Green Bay" "GRB"
       "NC" "Greensboro" "GSO"
       "MS" "Greenville" "GLH"
       "NC" "Greenville" "PGV"
       "SC" "Greenville/Spartanburg" "GSP"
       "CT" "Groton/New London" "GON"
       "MS" "Gulfport" "GPT"
       "CO" "Gunnison" "GUC"
       "AK" "Gustavus" "GST"
       "MD" "Hagerstown" "HGR"
       "ID" "Hailey" "SUN"
       "AK" "Haines" "HNS"
       "VA" "Hampton" "PHF"
       "HI - Island of Maui" "Hana" "HNM"
       "HI" "Hanapepe" "PAK"
       "MI" "Hancock" "CMX"
       "NH" "Hanover" "LEB"
       "TX" "Harlingen" "HRL"
       "PA" "Harrisburg" "MDT"
       "AR" "Harrison" "HRO"
       "CT" "Hartford" "BDL"
       "AZ" "Havasupai" "HAE"
       "MT" "Havre" "HVR"
       "CO" "Hayden" "HDN"
       "KS" "Hays" "HYS"
       "AK" "Healy Lake" "HKB"
       "MT" "Helena" "HLN"
       "NC" "Hendersonville" "AVL"
       "MN" "Hibbing/Chisholm" "HIB"
       "NC" "Hickory" "HKY"
       "NC" "High Point" "GSO"
       "HI - Island of Hawaii" "Hilo" "ITO"
       "SC" "Hilton Head" "HHH"
       "NM" "Hobbs" "HBB"
       "AK" "Hollis" "HYL"
       "AK" "Holy Cross" "HCR"
       "AK" "Homer" "HOM"
       "HI - Island of Oahu" "Honolulu" "HNL"
       "HI - Island of Molokai" "Hoolehua" "MKK"
       "AK" "Hoonah" "HNH"
       "AK" "Hooper Bay" "HPB"
       "AR" "Hot Springs" "HOT"
       "TX - All airports" "Houston" "HOU"
       "TX - Hobby" "Houston" "HOU"
       "TX - Intercontinental" "Houston" "IAH"
       "AK" "Hughes" "HUS"
       "WV/Ashland, KY" "Huntington" "HTS"
       "AL" "Huntsville" "HSV"
       "SD" "Huron" "HON"
       "AK" "Huslia" "HSL"
       "MA" "Hyannis" "HYA"
       "AK" "Hydaburg" "HYG"
       "ID" "Idaho Falls" "IDA"
       "AK" "Igiugig" "IGG"
       "AK" "Iliamna" "ILI"
       "CA" "Imperial" "IPL"
       "IN" "Indianapolis" "IND"
       "MN" "International Falls" "INL"
       "CA" "Inyokern" "IYK"
       "MI" "Iron Mountain" "IMT"
       "MI" "Ironwood" "IWD"
       "NY" "Islip" "ISP"
       "NY" "Ithaca" "ITH"
       "WY" "Jackson Hole" "JAC"
       "MS" "Jackson" "JAN"
       "TN" "Jackson" "MKL"
       "FL" "Jacksonville" "JAX"
       "NC" "Jacksonville" "OAJ"
       "ND" "Jamestown" "JMS"
       "NY" "Jamestown" "JHW"
       "WI" "Janesville" "JVL"
       "NY" "Johnson City" "BGM"
       "TN" "Johnson City" "TRI"
       "PA" "Johnstown" "JST"
       "AR" "Jonesboro" "JBR"
       "MO" "Joplin" "JLN"
       "AK" "Juneau" "JNU"
       "HI - Island of Maui," "Kahului" "OGG"
       "AK" "Kake" "KAE"
       "AK" "Kakhonak" "KNK"
       "MI" "Kalamazoo" "AZO"
       "HI - Island of Molokai," "Kalaupapa" "LUP"
       "AK" "Kalskag" "KLG"
       "AK" "Kaltag" "KAL"
       "HI - Island of Hawaii," "Kamuela" "MUE"
       "MO" "Kansas City" "MCI"
       "HI - Island of Maui," "Kapalua" "JHM"
       "AK" "Kasaan" "KXA"
       "AK" "Kasigluk" "KUK"
       "HI" "Kauai Island/Lihue" "LIH"
       "NE" "Kearney" "EAR"
       "NH" "Keene" "EEN"
       "AK" "Kenai" "ENA"
       "AK" "Ketchikan" "KTN"
       "FL" "Key West" "EYW"
       "CO - Van service" "Keystone" "QKS"
       "AK" "Kiana" "IAN"
       "TX" "Kilgore/Gladewater" "GGG"
       "TX" "Killeen" "ILE"
       "AK" "King Cove" "KVC"
       "AK" "King Salmon" "AKN"
       "AZ" "Kingman" "IGM"
       "TN" "Kingsport" "TRI"
       "AK" "Kipnuk" "KPN"
       "MO" "Kirksville" "IRK"
       "AK" "Kivalina" "KVL"
       "OR" "Klamath Falls" "LMT"
       "AK" "Klawock" "KLW"
       "TN" "Knoxville" "TYS"
       "AK" "Kobuk" "OBU"
       "AK" "Kodiak" "ADQ"
       "HI - Island of Hawaii" "Kona" "KOA"
       "AK" "Kongiganak" "KKH"
       "AK" "Kotlik" "KOT"
       "AK" "Kotzebue" "OTZ"
       "AK" "Koyukuk" "KYU"
       "AK" "Kwethluk" "KWT"
       "AK" "Kwigillingok" "KWK"
       "WI" "La Crosse" "LSE"
       "IN" "Lafayette" "LAF"
       "LA" "Lafayette" "LFT"
       "LA" "Lake Charles" "LCH"
       "AZ" "Lake Havasu City" "HII"
       "AK" "Lake Minchumina" "LMA"
       "HI - Island of Lanai" "Lanai City" "LNY"
       "PA" "Lancaster" "LNS"
       "MI" "Lansing" "LAN"
       "WY" "Laramie" "LAR"
       "TX" "Laredo" "LRD"
       "NV" "Las Vegas" "LAS"
       "PA" "Latrobe" "LBE"
       "MS" "Laurel" "PIB"
       "OK" "Lawton" "LAW"
       "NH" "Lebanon" "LEB"
       "AK" "Levelock" "KLL"
       "WV" "Lewisburg" "LWB"
       "ID" "Lewiston" "LWS"
       "MT" "Lewistown" "LWT"
       "KY" "Lexington" "LEX"
       "KS" "Liberal" "LBL"
       "HI - Island of Kaui" "Lihue" "LIH"
       "NE" "Lincoln" "LNK"
       "AR" "Little Rock" "LIT"
       "CA" "Long Beach" "LGB"
       "TX" "Longview" "GGG"
       "WA" "Lopez Island" "LPS"
       "CA" "Los Angeles" "LAX"
       "KY" "Louisville" "SDF"
       "CO - Municipal Airport" "Loveland/Fort Collins" "FNL"
       "CO - Bus service" "Loveland/Fort Collins" "QWF"
       "TX" "Lubbock" "LBB"
       "GA" "Macon" "MCN"
       "WI" "Madison" "MSN"
       "OR" "Madras" "MDJ"
       "NH" "Manchester" "MHT"
       "KS" "Manhattan" "MHK"
       "MI" "Manistee" "MBL"
       "MN" "Mankato" "MKT"
       "AK" "Manley Hot Springs" "MLY"
       "AK" "Manokotak" "KMO"
       "OH/Parkersburg, WV" "Marietta" "PKB"
       "IL" "Marion" "MWA"
       "MI" "Marquette" "MQT"
       "AK" "Marshall" "MLL"
       "MA" "Martha's Vineyard" "MVY"
       "PA" "Martinsburg" "AOO"
       "IA" "Mason City" "MCW"
       "NY" "Massena" "MSS"
       "HI" "Maui" "OGG"
       "TX" "Mcallen" "MFE"
       "NE" "Mccook" "MCK"
       "AK" "Mcgrath" "MCG"
       "OR" "Medford" "MFR"
       "AK" "Mekoryuk" "MYU"
       "FL" "Melbourne" "MLB"
       "TN" "Memphis" "MEM"
       "CA" "Merced" "MCE"
       "MS" "Meridian" "MEI"
       "AK" "Metlakatla" "MTM"
       "AK" "Meyers Chuck" "WMK"
       "FL - International" "Miami" "MIA"
       "FL - Sea Plane Base" "Miami" "MPB"
       "MI" "Midland" "MBS"
       "TX" "Midland/Odessa" "MAF"
       "MT" "Miles City" "MLS"
       "WI" "Milwaukee" "MKE"
       "MN" "Minneapolis" "MSP"
       "ND" "Minot" "MOT"
       "AK" "Minto" "MNT"
       "TX" "Mission" "MFE"
       "MT" "Missoula" "MSO"
       "UT" "Moab" "CNY"
       "AL" "Mobile" "MOB"
       "CA" "Modesto" "MOD"
       "IL" "Moline" "MLI"
       "LA" "Monroe" "MLU"
       "CA" "Monterey" "MRY"
       "AL" "Montgomery" "MGM"
       "CO" "Montrose" "MTJ"
       "WV" "Morgantown" "MGW"
       "WA" "Moses Lake" "MWH"
       "AR" "Mountain Home" "WMH"
       "AK" "Mountain Village" "MOU"
       "AL" "Muscle Shoals" "MSL"
       "MI" "Muskegon" "MKG"
       "SC" "Myrtle Beach" "MYR"
       "MA" "Nantucket" "ACK"
       "AK" "Napakiak" "WNA"
       "AK" "Napaskiak" "PKA"
       "FL" "Naples" "APF"
       "TN" "Nashville" "BNA"
       "AK" "Naukiti" "NKI"
       "AK" "Nelson Lagoon" "NLG"
       "AK" "New Chenega" "NCN"
       "CT" "New Haven" "HVN"
       "AK" "New Koliganek" "KGK"
       "AK" "New Koliganek" "KGK"
       "LA" "New Orleans" "MSY"
       "AK" "New Stuyahok" "KNW"
       "NY - All airports" "New York" "NYC"
       "NY - Kennedy" "New York" "JFK"
       "NY - La Guardia" "New York" "LGA"
       "NJ" "Newark" "EWR"
       "NY" "Newburgh/Stewart Field" "SWF"
       "VA" "Newport News" "PHF"
       "AK" "Newtok" "WWT"
       "AK" "Nightmute" "NME"
       "AK" "Nikolai" "NIB"
       "AK" "Nikolski" "IKO"
       "AK" "Noatak" "WTK"
       "AK" "Nome" "OME"
       "AK" "Nondalton" "NNL"
       "AK" "Noorvik" "ORV"
       "NE" "Norfolk" "OFK"
       "VA" "Norfolk" "ORF"
       "OR" "North Bend" "OTH"
       "NE" "North Platte" "LBF"
       "AK" "Northway" "ORT"
       "AK" "Nuiqsut" "NUI"
       "AK" "Nulato" "NUL"
       "AK" "Nunapitchuk" "NUP"
       "CA" "Oakland" "OAK"
       "TX" "Odessa/Midland" "MAF"
       "NY" "Ogdensburg" "OGS"
       "OK" "Oklahoma City" "OKC"
       "NE" "Omaha" "OMA"
       "CA" "Ontario" "ONT"
       "CA" "Orange County" "SNA"
       "FL - Herndon" "Orlando" "ORL"
       "FL - International" "Orlando" "MCO"
       "WI" "Oshkosh" "OSH"
       "IA" "Ottumwa" "OTM"
       "KY" "Owensboro" "OWB"
       "CA" "Oxnard/Ventura" "OXR"
       "KY" "Paducah" "PAH"
       "AZ" "Page" "PGA"
       "CA" "Palm Springs" "PSP"
       "FL" "Panama City" "PFN"
       "WV/Marietta, OH" "Parkersburg" "PKB"
       "WA" "Pasco" "PSC"
       "AK" "Pedro Bay" "PDB"
       "AK" "Pelican" "PEC"
       "MI" "Pellston" "PLN"
       "OR" "Pendleton" "PDT"
       "FL" "Pensacola" "PNS"
       "IL" "Peoria" "PIA"
       "AK" "Perryville" "KPV"
       "AK" "Petersburg" "PSG"
       "PA - International" "Philadelphia" "PHL"
       "PA - Trenton/Mercer NJ" "Philadelphia" "TTN"
       "AZ" "Phoenix" "PHX"
       "SD" "Pierre" "PIR"
       "AK - Ugashnik Bay" "Pilot Point" "UGB"
       "AK" "Pilot Point" "PIP"
       "AK" "Pilot Station" "PQS"
       "PA" "Pittsburgh" "PIT"
       "AK" "Platinum" "PTU"
       "NY" "Plattsburgh" "PLB"
       "ID" "Pocatello" "PIH"
       "AK" "Point Baker" "KPB"
       "AK" "Point Hope" "PHO"
       "AK" "Point Lay" "PIZ"
       "OK" "Ponca City" "PNC"
       "Puerto Rico" "Ponce" "PSE"
       "AK" "Port Alsworth" "PTA"
       "WA" "Port Angeles" "CLM"
       "TX" "Port Arthur/Beaumont" "BPT"
       "AK" "Port Clarence" "KPC"
       "AK" "Port Heiden" "PTH"
       "AK" "Port Moller" "PML"
       "AK" "Port Protection" "PPV"
       "AK" "Portage Creek" "PCA"
       "ME" "Portland" "PWM"
       "OR" "Portland" "PDX"
       "NH" "Portsmouth" "PSM"
       "NY" "Poughkeepsie" "POU"
       "AZ" "Prescott" "PRC"
       "ME" "Presque Isle" "PQI"
       "WV" "Princeton" "BLF"
       "RI" "Providence" "PVD"
       "MA" "Provincetown" "PVC"
       "AK" "Prudhoe Bay/Deadhorse" "SCC"
       "CO" "Pueblo" "PUB"
       "WA" "Pullman" "PUW"
       "IL" "Quincy" "UIN"
       "AK" "Quinhagak" "KWN"
       "NC" "Raleigh/Durham" "RDU"
       "AK" "Rampart" "RMP"
       "SD" "Rapid City" "RAP"
       "PA" "Reading" "RDG"
       "AK" "Red Devil" "RDV"
       "CA" "Redding" "RDD"
       "OR" "Redmond" "RDM"
       "NV" "Reno" "RNO"
       "WI," "Rhinelander" "RHI"
       "VA" "Richmond" "RIC"
       "WY" "Riverton" "RIW"
       "VA" "Roanoke" "ROA"
       "WA" "Roche Harbor" "RCE"
       "MN" "Rochester" "RST"
       "NY" "Rochester" "ROC"
       "WY" "Rock Springs" "RKS"
       "IL - Park&Ride Bus" "Rockford" "ZRF"
       "IL - Van Galder Bus" "Rockford" "ZRK"
       "ME" "Rockland" "RKD"
       "WA" "Rosario" "RSJ"
       "NM" "Roswell" "ROW"
       "AK" "Ruby" "RBY"
       "AK" "Russian Mission" "RSH"
       "VT" "Rutland" "RUT"
       "CA" "Sacramento" "SMF"
       "MI" "Saginaw" "MBS"
       "MN" "Saint Cloud" "STC"
       "AK" "Saint George Island" "STG"
       "UT" "Saint George" "SGU"
       "MO" "Saint Louis" "STL"
       "AK" "Saint Mary's" "KSM"
       "AK" "Saint Michael" "SMK"
       "AK" "Saint Paul Island" "SNP"
       "OR" "Salem" "SLE"
       "KS" "Salina" "SLN"
       "MD" "Salisbury-Ocean City" "SBY"
       "UT" "Salt Lake City" "SLC"
       "TX" "San Angelo" "SJT"
       "TX" "San Antonio" "SAT"
       "CA" "San Diego" "SAN"
       "CA" "San Francisco" "SFO"
       "CA" "San Jose" "SJC"
       "Puerto Rico" "San Juan" "SJU"
       "CA" "San Luis Obispo" "SBP"
       "AK" "Sand Point" "SDP"
       "CA" "Santa Ana" "SNA"
       "CA" "Santa Barbara" "SBA"
       "NM" "Santa Fe" "SAF"
       "CA" "Santa Maria" "SMX"
       "CA" "Santa Rosa" "STS"
       "NY" "Saranac Lake" "SLK"
       "FL" "Sarasota" "SRQ"
       "MI," "Sault Ste Marie" "CIU"
       "GA" "Savannah" "SAV"
       "AK" "Savoonga" "SVA"
       "AK" "Scammon Bay" "SCM"
       "NE" "Scottsbluff" "BFF"
       "PA" "Scranton" "AVP"
       "WA - Lake Union SPB" "Seattle" "LKE"
       "WA - Seattle/Tacoma International" "Seattle" "SEA"
       "AK" "Selawik" "WLK"
       "AK" "Seward" "SWD"
       "AK" "Shageluk" "SHX"
       "AK" "Shaktoolik" "SKK"
       "AL" "Sheffield/Florence/Muscle Shoals" "MSL"
       "AK" "Sheldon Point" "SXP"
       "WY" "Sheridan" "SHR"
       "AK" "Shishmaref" "SHH"
       "LA" "Shreveport" "SHV"
       "AK" "Shungnak" "SHG"
       "NM" "Silver City" "SVC"
       "IA" "Sioux City" "SUX"
       "SD" "Sioux Falls" "FSD"
       "AK" "Sitka" "SIT"
       "AK" "Skagway" "SGY"
       "AK" "Sleetmore" "SLQ"
       "IN" "South Bend" "SBN"
       "AK" "South Naknek" "WSN"
       "NC" "Southern Pines" "SOP"
       "SC" "Spartanburg/Greenville" "GSP"
       "WA" "Spokane" "GEG"
       "IL" "Springfield" "SPI"
       "MO" "Springfield" "SGF"
       "FL" "St Petersburg/Clearwater" "PIE"
       "PA" "State College/University Park" "SCE"
       "VA" "Staunton" "SHD"
       "CO" "Steamboat Springs" "SBS"
       "AK" "Stebbins" "WBB"
       "WI" "Stevens Point/Wausau" "CWA"
       "AK" "Stevens Village" "SVS"
       "NY" "Stewart Field/Newburgh" "SWF"
       "CA" "Stockton" "SCK"
       "AK" "Stony River" "SRV"
       "ID" "Sun Valley" "SUN"
       "NY" "Syracuse" "SYR"
       "AK" "Takotna" "TCT"
       "AK" "Talkeetna" "TKA"
       "FL" "Tallahassee" "TLH"
       "FL" "Tampa" "TPA"
       "AK" "Tanana" "TAL"
       "NM" "Taos" "TSM"
       "AK" "Tatitlek" "TEK"
       "AK" "Teller Mission" "KTS"
       "CO" "Telluride" "TEX"
       "AK" "Tenakee Springs" "TKE"
       "IN" "Terre Haute" "HUF"
       "AK" "Tetlin" "TEH"
       "AR" "Texarkana" "TXK"
       "MN" "Thief River Falls" "TVF"
       "AK" "Thorne Bay" "KTB"
       "AK" "Tin City" "TNC"
       "AK" "Togiak Village" "TOG"
       "AK" "Tok" "TKJ"
       "AK" "Toksook Bay" "OOK"
       "OH" "Toledo" "TOL"
       "KS" "Topeka" "FOE"
       "MI" "Traverse City" "TVC"
       "NJ" "Trenton/Mercer" "TTN"
       "AZ" "Tucson" "TUS"
       "OK" "Tulsa" "TUL"
       "AK" "Tuluksak" "TLT"
       "AK" "Tuntutuliak" "WTL"
       "AK" "Tununak" "TNK"
       "MS" "Tupelo" "TUP"
       "AL" "Tuscaloosa" "TCL"
       "ID" "Twin Falls" "TWF"
       "AK" "Twin Hills" "TWA"
       "TX" "Tyler" "TYR"
       "AK" "Unalakleet" "UNK"
       "IL" "Urbana/Champaign" "CMI"
       "NY" "Utica" "UCA"
       "AK" "Utopia Creek" "UTO"
       "CO - Eagle County Airport" "Vail" "EGE"
       "CO - Van service" "Vail" "QBF"
       "AK" "Valdez" "VDZ"
       "GA" "Valdosta" "VLD"
       "FL" "Valparaiso" "VPS"
       "AK" "Venetie" "VEE"
       "CA" "Ventura/Oxnard" "OXR"
       "UT" "Vernal" "VEL"
       "TX" "Victoria" "VCT"
       "CA" "Visalia" "VIS"
       "TX" "Waco" "ACT"
       "AK" "Wainwright" "AIN"
       "AK" "Wales" "WAA"
       "WA" "Walla Walla" "ALW"
       "WA" "Walla Walla" "ALW"
       "WA" "Walla Walla" "ALW"
       "WA" "Walla Walla" "ALW"
       "AK" "Waterfall" "KWF"
       "IA" "Waterloo" "ALO"
       "NY" "Watertown" "ART"
       "SD" "Watertown" "ATY"
       "WI" "Wausau/Stevens Point" "CWA"
       "WA" "Wenatchee" "EAT"
       "FL" "West Palm Beach" "PBI"
       "MT" "West Yellowstone" "WYS"
       "NY" "Westchester County" "HPN"
       "RI" "Westerly" "WST"
       "WA" "Westsound" "WSX"
       "AK" "Whale Pass" "WWP"
       "AK" "White Mountain" "WMO"
       "VT" "White River" "LEB"
       "TX" "Wichita Falls" "SPS"
       "KS" "Wichita" "ICT"
       "PA" "Wilkes Barre" "AVP"
       "VA" "Williamsburg" "PHF"
       "PA" "Williamsport" "IPT"
       "ND" "Williston" "ISN"
       "NC" "Wilmington" "ILM"
       "CT" "Windsor Locks" "BDL"
       "MA" "Worcester" "ORH"
       "WY" "Worland" "WRL"
       "AK" "Wrangell" "WRG"
       "WA" "Yakima" "YKM"
       "AK" "Yakutat" "YAK"
       "WY" "Yellowstone/Cody" "COD"
       "OH" "Youngstown" "YNG"
       "AZ" "Yuma" "YUM"
       ]))

;; regexes pulled from Regex::Common CPAN module
(def *common-regexes* 
  {:num-real #"(?-xism:(?:(?i)(?:[+-]?)(?:(?=[0123456789]|[.])(?:[0123456789]*)(?:(?:[.])(?:[0123456789]{0,}))?)(?:(?:[E])(?:(?:[+-]?)(?:[0123456789]+))|)))"
   :num-int #"(?-xism:(?:(?:[+-]?)(?:[0123456789]+)))"
   :num-decimal #"(?-xism:(?:(?i)(?:[+-]?)(?:(?=[0123456789]|[.])(?:[0123456789]*)(?:(?:[.])(?:[0123456789]{0,}))?)))"
   :num-hex #"(?-xism:(?:(?i)(?:[+-]?)(?:(?=[0123456789ABCDEF]|[.])(?:[0123456789ABCDEF]*)(?:(?:[.])(?:[0123456789ABCDEF]{0,}))?)(?:(?:[G])(?:(?:[+-]?)(?:[0123456789ABCDEF]+))|)))"
   :num-dec #"(?-xism:(?:(?i)(?:[+-]?)(?:(?=[0123456789]|[.])(?:[0123456789]*)(?:(?:[.])(?:[0123456789]{0,}))?)(?:(?:[E])(?:(?:[+-]?)(?:[0123456789]+))|)))"
   :num-oct #"(?-xism:(?:(?i)(?:[+-]?)(?:(?=[01234567]|[.])(?:[01234567]*)(?:(?:[.])(?:[01234567]{0,}))?)(?:(?:[E])(?:(?:[+-]?)(?:[01234567]+))|)))"
   :num-bin #"(?-xism:(?:(?i)(?:[+-]?)(?:(?=[01]|[.])(?:[01]*)(?:(?:[.])(?:[01]{0,}))?)(?:(?:[E])(?:(?:[+-]?)(?:[01]+))|)))"
   :num-roman #"(?-xism:(?xi)(?=[MDCLXVI])
                         (?:M{0,3}
                            (D?C{0,3}|CD|CM)?
                            (L?X{0,3}|XL|XC)?
                            (V?I{0,3}|IV|IX)?))"
   :zip #"(?-xism:(?:(?:(?:USA?)-){0,1}(?:(?:(?:[0-9]{3})(?:[0-9]{2}))(?:(?:-)(?:(?:[0-9]{2})(?:[0-9]{2}))){0,1})))"
   :net-ipv4 #"(?-xism:(?:(?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2})[.](?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2})[.](?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2})[.](?:25[0-5]|2[0-4][0-9]|[0-1]?[0-9]{1,2})))"
   :net-mac #"(?-xism:(?:(?:[0-9a-fA-F]{1,2}):(?:[0-9a-fA-F]{1,2}):(?:[0-9a-fA-F]{1,2}):(?:[0-9a-fA-F]{1,2}):(?:[0-9a-fA-F]{1,2}):(?:[0-9a-fA-F]{1,2})))"
   :net-domain #"(?-xism:(?: |(?:[A-Za-z](?:(?:[-A-Za-z0-9]){0,61}[A-Za-z0-9])?(?:\.[A-Za-z](?:(?:[-A-Za-z0-9]){0,61}[A-Za-z0-9])?)*)))"
   :phone #"(?:1[- ]?)?\(?[2-9]\d{2}\)?[-\. ]?\d{3}[-\. ]?\d{4}(?:\s*(?:e|ex|ext|x|xtn|extension)?\s*\d*)"
   :us-states        (Pattern/compile (format "(?-xism:%s)" (str/str-join "|" (keys *us-states*))))
   :us-state-names   (Pattern/compile (format "(?-xism:%s)" (str/str-join "|" (vals *us-states*))))
   :us-airport-codes (Pattern/compile (format "(?-xism:%s)" (str/str-join "|" (map #(nth % 2) *us-airport-codes*))))
   })

;; (re-find (:us-airport-codes *common-regexes*) "foo PHL bar")


;; (:us-state-names *common-regexes*)
;; (:us-states *common-regexes*)
;; (re-matches (:zip *common-regexes*) "19087")



;; (re-matches (:phone *common-regexes*) "1 (610) 940 4002 x 116")
;; (re-matches (:phone *common-regexes*) "1 (610) 940 4002x116")
;; (re-matches (:phone *common-regexes*) "(610) 940 4002 x 116")
;; (re-matches (:phone *common-regexes*) "610.940.4002")
;; (re-matches (:phone *common-regexes*) "610.940.4002")
;; (re-matches (:phone *common-regexes*) "1610.940.4002")
;; (re-matches (:phone *common-regexes*) "1-610.940.4002")
;; (re-matches (:phone *common-regexes*) "1 610.940.4002")

